/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Mk1100pk0getOrderDocsUrlResponse implements Serializable {


    @ColumnAlias("poutOrderDocsUrl")
    private String poutOrderDocsUrl;

    public String getPoutOrderDocsUrl() {
        return this.poutOrderDocsUrl;
    }

    public void setPoutOrderDocsUrl(String poutOrderDocsUrl) {
        this.poutOrderDocsUrl = poutOrderDocsUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Mk1100pk0getOrderDocsUrlResponse)) return false;
        final Mk1100pk0getOrderDocsUrlResponse mk1100pk0getOrderDocsUrlResponse = (Mk1100pk0getOrderDocsUrlResponse) o;
        return Objects.equals(getPoutOrderDocsUrl(), mk1100pk0getOrderDocsUrlResponse.getPoutOrderDocsUrl());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrderDocsUrl());
    }
}