/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Mk1100pk0getMenuItemsResponsePoutMenuItems implements Serializable {


    @ColumnAlias("ITEMSEQ")
    private Byte itemseq;

    @ColumnAlias("PROGNAME")
    private String progname;

    @ColumnAlias("PARAMS")
    private String params;

    @ColumnAlias("WMPARAMS")
    private String wmparams;

    @ColumnAlias("PROGURL")
    private String progurl;

    @ColumnAlias("WMITEMPATH")
    private String wmitempath;

    public Byte getItemseq() {
        return this.itemseq;
    }

    public void setItemseq(Byte itemseq) {
        this.itemseq = itemseq;
    }

    public String getProgname() {
        return this.progname;
    }

    public void setProgname(String progname) {
        this.progname = progname;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getWmparams() {
        return this.wmparams;
    }

    public void setWmparams(String wmparams) {
        this.wmparams = wmparams;
    }

    public String getProgurl() {
        return this.progurl;
    }

    public void setProgurl(String progurl) {
        this.progurl = progurl;
    }

    public String getWmitempath() {
        return this.wmitempath;
    }

    public void setWmitempath(String wmitempath) {
        this.wmitempath = wmitempath;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Mk1100pk0getMenuItemsResponsePoutMenuItems)) return false;
        final Mk1100pk0getMenuItemsResponsePoutMenuItems mk1100pk0getMenuItemsResponsePoutMenuItems = (Mk1100pk0getMenuItemsResponsePoutMenuItems) o;
        return Objects.equals(getItemseq(), mk1100pk0getMenuItemsResponsePoutMenuItems.getItemseq()) &&
                Objects.equals(getProgname(), mk1100pk0getMenuItemsResponsePoutMenuItems.getProgname()) &&
                Objects.equals(getParams(), mk1100pk0getMenuItemsResponsePoutMenuItems.getParams()) &&
                Objects.equals(getWmparams(), mk1100pk0getMenuItemsResponsePoutMenuItems.getWmparams()) &&
                Objects.equals(getProgurl(), mk1100pk0getMenuItemsResponsePoutMenuItems.getProgurl()) &&
                Objects.equals(getWmitempath(), mk1100pk0getMenuItemsResponsePoutMenuItems.getWmitempath());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemseq(),
                getProgname(),
                getParams(),
                getWmparams(),
                getProgurl(),
                getWmitempath());
    }
}