/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Mk1100pk0getMenuItemsResponse implements Serializable {


    @ColumnAlias("poutMenuItems")
    private List<Mk1100pk0getMenuItemsResponsePoutMenuItems> poutMenuItems;

    public List<Mk1100pk0getMenuItemsResponsePoutMenuItems> getPoutMenuItems() {
        return this.poutMenuItems;
    }

    public void setPoutMenuItems(List<Mk1100pk0getMenuItemsResponsePoutMenuItems> poutMenuItems) {
        this.poutMenuItems = poutMenuItems;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Mk1100pk0getMenuItemsResponse)) return false;
        final Mk1100pk0getMenuItemsResponse mk1100pk0getMenuItemsResponse = (Mk1100pk0getMenuItemsResponse) o;
        return Objects.equals(getPoutMenuItems(), mk1100pk0getMenuItemsResponse.getPoutMenuItems());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMenuItems());
    }
}