/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk450jobUnloadperszeResponse implements Serializable {


    @ColumnAlias("poutJobSzeUnLoadQty")
    private List<ProcMk1100pk0Mk450jobUnloadperszeResponsePoutJobSzeUnLoadQty> poutJobSzeUnLoadQty;

    public List<ProcMk1100pk0Mk450jobUnloadperszeResponsePoutJobSzeUnLoadQty> getPoutJobSzeUnLoadQty() {
        return this.poutJobSzeUnLoadQty;
    }

    public void setPoutJobSzeUnLoadQty(List<ProcMk1100pk0Mk450jobUnloadperszeResponsePoutJobSzeUnLoadQty> poutJobSzeUnLoadQty) {
        this.poutJobSzeUnLoadQty = poutJobSzeUnLoadQty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk450jobUnloadperszeResponse)) return false;
        final ProcMk1100pk0Mk450jobUnloadperszeResponse procMk1100pk0mk450jobUnloadperszeResponse = (ProcMk1100pk0Mk450jobUnloadperszeResponse) o;
        return Objects.equals(getPoutJobSzeUnLoadQty(), procMk1100pk0mk450jobUnloadperszeResponse.getPoutJobSzeUnLoadQty());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutJobSzeUnLoadQty());
    }
}