/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty implements Serializable {


    @ColumnAlias("DYEJOB")
    private String dyejob;

    @ColumnAlias("MAKEUPUNIT")
    private String makeupunit;

    @ColumnAlias("LOAD_GOODQTY")
    private BigInteger loadGoodqty;

    @ColumnAlias("LOAD_BLUEQTY")
    private BigInteger loadBlueqty;

    @ColumnAlias("LOAD_REDQTY")
    private BigInteger loadRedqty;

    @ColumnAlias("UNLOAD_GOODQTY")
    private BigInteger unloadGoodqty;

    @ColumnAlias("UNLOAD_BLUEQTY")
    private BigInteger unloadBlueqty;

    @ColumnAlias("UNLOAD_REDQTY")
    private BigInteger unloadRedqty;

    @ColumnAlias("DIFF_GOOD")
    private BigInteger diffGood;

    @ColumnAlias("DIFF_BLUE")
    private BigInteger diffBlue;

    @ColumnAlias("DIFF_RED")
    private BigInteger diffRed;

    public String getDyejob() {
        return this.dyejob;
    }

    public void setDyejob(String dyejob) {
        this.dyejob = dyejob;
    }

    public String getMakeupunit() {
        return this.makeupunit;
    }

    public void setMakeupunit(String makeupunit) {
        this.makeupunit = makeupunit;
    }

    public BigInteger getLoadGoodqty() {
        return this.loadGoodqty;
    }

    public void setLoadGoodqty(BigInteger loadGoodqty) {
        this.loadGoodqty = loadGoodqty;
    }

    public BigInteger getLoadBlueqty() {
        return this.loadBlueqty;
    }

    public void setLoadBlueqty(BigInteger loadBlueqty) {
        this.loadBlueqty = loadBlueqty;
    }

    public BigInteger getLoadRedqty() {
        return this.loadRedqty;
    }

    public void setLoadRedqty(BigInteger loadRedqty) {
        this.loadRedqty = loadRedqty;
    }

    public BigInteger getUnloadGoodqty() {
        return this.unloadGoodqty;
    }

    public void setUnloadGoodqty(BigInteger unloadGoodqty) {
        this.unloadGoodqty = unloadGoodqty;
    }

    public BigInteger getUnloadBlueqty() {
        return this.unloadBlueqty;
    }

    public void setUnloadBlueqty(BigInteger unloadBlueqty) {
        this.unloadBlueqty = unloadBlueqty;
    }

    public BigInteger getUnloadRedqty() {
        return this.unloadRedqty;
    }

    public void setUnloadRedqty(BigInteger unloadRedqty) {
        this.unloadRedqty = unloadRedqty;
    }

    public BigInteger getDiffGood() {
        return this.diffGood;
    }

    public void setDiffGood(BigInteger diffGood) {
        this.diffGood = diffGood;
    }

    public BigInteger getDiffBlue() {
        return this.diffBlue;
    }

    public void setDiffBlue(BigInteger diffBlue) {
        this.diffBlue = diffBlue;
    }

    public BigInteger getDiffRed() {
        return this.diffRed;
    }

    public void setDiffRed(BigInteger diffRed) {
        this.diffRed = diffRed;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty)) return false;
        final ProcMk1100pk0Mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty = (ProcMk1100pk0Mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty) o;
        return Objects.equals(getDyejob(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getDyejob()) &&
                Objects.equals(getMakeupunit(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getMakeupunit()) &&
                Objects.equals(getLoadGoodqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getLoadGoodqty()) &&
                Objects.equals(getLoadBlueqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getLoadBlueqty()) &&
                Objects.equals(getLoadRedqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getLoadRedqty()) &&
                Objects.equals(getUnloadGoodqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getUnloadGoodqty()) &&
                Objects.equals(getUnloadBlueqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getUnloadBlueqty()) &&
                Objects.equals(getUnloadRedqty(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getUnloadRedqty()) &&
                Objects.equals(getDiffGood(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getDiffGood()) &&
                Objects.equals(getDiffBlue(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getDiffBlue()) &&
                Objects.equals(getDiffRed(), procMk1100pk0mk440getjobLoadunldqtyResponsePoutJobLdUnloadQty.getDiffRed());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDyejob(),
                getMakeupunit(),
                getLoadGoodqty(),
                getLoadBlueqty(),
                getLoadRedqty(),
                getUnloadGoodqty(),
                getUnloadBlueqty(),
                getUnloadRedqty(),
                getDiffGood(),
                getDiffBlue(),
                getDiffRed());
    }
}