/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk570getProdDetailsResponse implements Serializable {


    @ColumnAlias("poutProdDet")
    private List<ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet> poutProdDet;

    public List<ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet> getPoutProdDet() {
        return this.poutProdDet;
    }

    public void setPoutProdDet(List<ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet> poutProdDet) {
        this.poutProdDet = poutProdDet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk570getProdDetailsResponse)) return false;
        final ProcMk1100pk0Mk570getProdDetailsResponse procMk1100pk0mk570getProdDetailsResponse = (ProcMk1100pk0Mk570getProdDetailsResponse) o;
        return Objects.equals(getPoutProdDet(), procMk1100pk0mk570getProdDetailsResponse.getPoutProdDet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutProdDet());
    }
}