/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk103pk0ordqryGetOrdcommentResponse implements Serializable {


    @ColumnAlias("pOutCommentsList")
    private List<ProcMk103pk0ordqryGetOrdcommentResponsePoutCommentsList> poutCommentsList;

    public List<ProcMk103pk0ordqryGetOrdcommentResponsePoutCommentsList> getPoutCommentsList() {
        return this.poutCommentsList;
    }

    public void setPoutCommentsList(List<ProcMk103pk0ordqryGetOrdcommentResponsePoutCommentsList> poutCommentsList) {
        this.poutCommentsList = poutCommentsList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk103pk0ordqryGetOrdcommentResponse)) return false;
        final ProcMk103pk0ordqryGetOrdcommentResponse procMk103pk0ordqryGetOrdcommentResponse = (ProcMk103pk0ordqryGetOrdcommentResponse) o;
        return Objects.equals(getPoutCommentsList(), procMk103pk0ordqryGetOrdcommentResponse.getPoutCommentsList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCommentsList());
    }
}