/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0GetOrt150sizeResponsePoutSizes implements Serializable {


    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("SZEDES")
    private String szedes;

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public String getSzedes() {
        return this.szedes;
    }

    public void setSzedes(String szedes) {
        this.szedes = szedes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0GetOrt150sizeResponsePoutSizes)) return false;
        final ProcMk1100pk0GetOrt150sizeResponsePoutSizes procMk1100pk0getOrt150sizeResponsePoutSizes = (ProcMk1100pk0GetOrt150sizeResponsePoutSizes) o;
        return Objects.equals(getSzeseq(), procMk1100pk0getOrt150sizeResponsePoutSizes.getSzeseq()) &&
                Objects.equals(getSzedes(), procMk1100pk0getOrt150sizeResponsePoutSizes.getSzedes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSzeseq(),
                getSzedes());
    }
}