/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0QryMk721prodminsResponsePoutProdmins implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("GMTDES")
    private String gmtdes;

    @ColumnAlias("MAKLCN")
    private String maklcn;

    @ColumnAlias("SUBLCNCOD")
    private String sublcncod;

    @ColumnAlias("PRODDATE")
    private LocalDateTime proddate;

    @ColumnAlias("MKLINE")
    private String mkline;

    @ColumnAlias("NUMOPER")
    private Short numoper;

    @ColumnAlias("STARTTIME")
    private LocalDateTime starttime;

    @ColumnAlias("ENDTIME")
    private LocalDateTime endtime;

    @ColumnAlias("EFFWRKMIN")
    private Integer effwrkmin;

    @ColumnAlias("PREPMIN")
    private BigDecimal prepmin;

    @ColumnAlias("TARSEWMIN")
    private BigDecimal tarsewmin;

    @ColumnAlias("PDDMIN_PREP")
    private BigDecimal pddminPrep;

    @ColumnAlias("STDMIN")
    private BigDecimal stdmin;

    @ColumnAlias("PDDMIN")
    private BigDecimal pddmin;

    @ColumnAlias("TARGETQTY")
    private BigDecimal targetqty;

    @ColumnAlias("PRODQTY")
    private BigDecimal prodqty;

    @ColumnAlias("EFFPERCENT")
    private BigDecimal effpercent;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("CLINAM")
    private String clinam;

    @ColumnAlias("WSTYLE")
    private String wstyle;

    @ColumnAlias("WTOTMINS")
    private BigDecimal wtotmins;

    @ColumnAlias("WACTMINS")
    private BigDecimal wactmins;

    @ColumnAlias("WHDACTMINS")
    private BigDecimal whdactmins;

    @ColumnAlias("WTOTACTMINS")
    private BigDecimal wtotactmins;

    @ColumnAlias("WTOTGMTMIN")
    private BigDecimal wtotgmtmin;

    @ColumnAlias("SUMMINUTES")
    private BigDecimal summinutes;

    @ColumnAlias("SUMPCS")
    private BigDecimal sumpcs;

    @ColumnAlias("SUMTARGETPCS")
    private BigDecimal sumtargetpcs;

    @ColumnAlias("MINEFF")
    private BigDecimal mineff;

    @ColumnAlias("MAXEFF")
    private BigDecimal maxeff;

    @ColumnAlias("AVGEFF")
    private BigDecimal avgeff;

    @ColumnAlias("MINOPERACTMINS")
    private BigDecimal minoperactmins;

    @ColumnAlias("MAXOPERACTMINS")
    private BigDecimal maxoperactmins;

    @ColumnAlias("AVGOPERACTMINS")
    private BigDecimal avgoperactmins;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public String getGmtdes() {
        return this.gmtdes;
    }

    public void setGmtdes(String gmtdes) {
        this.gmtdes = gmtdes;
    }

    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    public String getSublcncod() {
        return this.sublcncod;
    }

    public void setSublcncod(String sublcncod) {
        this.sublcncod = sublcncod;
    }

    public LocalDateTime getProddate() {
        return this.proddate;
    }

    public void setProddate(LocalDateTime proddate) {
        this.proddate = proddate;
    }

    public String getMkline() {
        return this.mkline;
    }

    public void setMkline(String mkline) {
        this.mkline = mkline;
    }

    public Short getNumoper() {
        return this.numoper;
    }

    public void setNumoper(Short numoper) {
        this.numoper = numoper;
    }

    public LocalDateTime getStarttime() {
        return this.starttime;
    }

    public void setStarttime(LocalDateTime starttime) {
        this.starttime = starttime;
    }

    public LocalDateTime getEndtime() {
        return this.endtime;
    }

    public void setEndtime(LocalDateTime endtime) {
        this.endtime = endtime;
    }

    public Integer getEffwrkmin() {
        return this.effwrkmin;
    }

    public void setEffwrkmin(Integer effwrkmin) {
        this.effwrkmin = effwrkmin;
    }

    public BigDecimal getPrepmin() {
        return this.prepmin;
    }

    public void setPrepmin(BigDecimal prepmin) {
        this.prepmin = prepmin;
    }

    public BigDecimal getTarsewmin() {
        return this.tarsewmin;
    }

    public void setTarsewmin(BigDecimal tarsewmin) {
        this.tarsewmin = tarsewmin;
    }

    public BigDecimal getPddminPrep() {
        return this.pddminPrep;
    }

    public void setPddminPrep(BigDecimal pddminPrep) {
        this.pddminPrep = pddminPrep;
    }

    public BigDecimal getStdmin() {
        return this.stdmin;
    }

    public void setStdmin(BigDecimal stdmin) {
        this.stdmin = stdmin;
    }

    public BigDecimal getPddmin() {
        return this.pddmin;
    }

    public void setPddmin(BigDecimal pddmin) {
        this.pddmin = pddmin;
    }

    public BigDecimal getTargetqty() {
        return this.targetqty;
    }

    public void setTargetqty(BigDecimal targetqty) {
        this.targetqty = targetqty;
    }

    public BigDecimal getProdqty() {
        return this.prodqty;
    }

    public void setProdqty(BigDecimal prodqty) {
        this.prodqty = prodqty;
    }

    public BigDecimal getEffpercent() {
        return this.effpercent;
    }

    public void setEffpercent(BigDecimal effpercent) {
        this.effpercent = effpercent;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getClinam() {
        return this.clinam;
    }

    public void setClinam(String clinam) {
        this.clinam = clinam;
    }

    public String getWstyle() {
        return this.wstyle;
    }

    public void setWstyle(String wstyle) {
        this.wstyle = wstyle;
    }

    public BigDecimal getWtotmins() {
        return this.wtotmins;
    }

    public void setWtotmins(BigDecimal wtotmins) {
        this.wtotmins = wtotmins;
    }

    public BigDecimal getWactmins() {
        return this.wactmins;
    }

    public void setWactmins(BigDecimal wactmins) {
        this.wactmins = wactmins;
    }

    public BigDecimal getWhdactmins() {
        return this.whdactmins;
    }

    public void setWhdactmins(BigDecimal whdactmins) {
        this.whdactmins = whdactmins;
    }

    public BigDecimal getWtotactmins() {
        return this.wtotactmins;
    }

    public void setWtotactmins(BigDecimal wtotactmins) {
        this.wtotactmins = wtotactmins;
    }

    public BigDecimal getWtotgmtmin() {
        return this.wtotgmtmin;
    }

    public void setWtotgmtmin(BigDecimal wtotgmtmin) {
        this.wtotgmtmin = wtotgmtmin;
    }

    public BigDecimal getSumminutes() {
        return this.summinutes;
    }

    public void setSumminutes(BigDecimal summinutes) {
        this.summinutes = summinutes;
    }

    public BigDecimal getSumpcs() {
        return this.sumpcs;
    }

    public void setSumpcs(BigDecimal sumpcs) {
        this.sumpcs = sumpcs;
    }

    public BigDecimal getSumtargetpcs() {
        return this.sumtargetpcs;
    }

    public void setSumtargetpcs(BigDecimal sumtargetpcs) {
        this.sumtargetpcs = sumtargetpcs;
    }

    public BigDecimal getMineff() {
        return this.mineff;
    }

    public void setMineff(BigDecimal mineff) {
        this.mineff = mineff;
    }

    public BigDecimal getMaxeff() {
        return this.maxeff;
    }

    public void setMaxeff(BigDecimal maxeff) {
        this.maxeff = maxeff;
    }

    public BigDecimal getAvgeff() {
        return this.avgeff;
    }

    public void setAvgeff(BigDecimal avgeff) {
        this.avgeff = avgeff;
    }

    public BigDecimal getMinoperactmins() {
        return this.minoperactmins;
    }

    public void setMinoperactmins(BigDecimal minoperactmins) {
        this.minoperactmins = minoperactmins;
    }

    public BigDecimal getMaxoperactmins() {
        return this.maxoperactmins;
    }

    public void setMaxoperactmins(BigDecimal maxoperactmins) {
        this.maxoperactmins = maxoperactmins;
    }

    public BigDecimal getAvgoperactmins() {
        return this.avgoperactmins;
    }

    public void setAvgoperactmins(BigDecimal avgoperactmins) {
        this.avgoperactmins = avgoperactmins;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0QryMk721prodminsResponsePoutProdmins)) return false;
        final ProcMk1100pk0QryMk721prodminsResponsePoutProdmins procMk1100pk0qryMk721prodminsResponsePoutProdmins = (ProcMk1100pk0QryMk721prodminsResponsePoutProdmins) o;
        return Objects.equals(getOrdnum(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getOrdnum()) &&
                Objects.equals(getClicod(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getClicod()) &&
                Objects.equals(getGmtseq(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getGmtseq()) &&
                Objects.equals(getGmtdes(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getGmtdes()) &&
                Objects.equals(getMaklcn(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMaklcn()) &&
                Objects.equals(getSublcncod(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getSublcncod()) &&
                Objects.equals(getProddate(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getProddate()) &&
                Objects.equals(getMkline(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMkline()) &&
                Objects.equals(getNumoper(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getNumoper()) &&
                Objects.equals(getStarttime(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getStarttime()) &&
                Objects.equals(getEndtime(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getEndtime()) &&
                Objects.equals(getEffwrkmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getEffwrkmin()) &&
                Objects.equals(getPrepmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getPrepmin()) &&
                Objects.equals(getTarsewmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getTarsewmin()) &&
                Objects.equals(getPddminPrep(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getPddminPrep()) &&
                Objects.equals(getStdmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getStdmin()) &&
                Objects.equals(getPddmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getPddmin()) &&
                Objects.equals(getTargetqty(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getTargetqty()) &&
                Objects.equals(getProdqty(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getProdqty()) &&
                Objects.equals(getEffpercent(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getEffpercent()) &&
                Objects.equals(getRemarks(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getRemarks()) &&
                Objects.equals(getClinam(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getClinam()) &&
                Objects.equals(getWstyle(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWstyle()) &&
                Objects.equals(getWtotmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWtotmins()) &&
                Objects.equals(getWactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWactmins()) &&
                Objects.equals(getWhdactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWhdactmins()) &&
                Objects.equals(getWtotactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWtotactmins()) &&
                Objects.equals(getWtotgmtmin(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getWtotgmtmin()) &&
                Objects.equals(getSumminutes(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getSumminutes()) &&
                Objects.equals(getSumpcs(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getSumpcs()) &&
                Objects.equals(getSumtargetpcs(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getSumtargetpcs()) &&
                Objects.equals(getMineff(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMineff()) &&
                Objects.equals(getMaxeff(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMaxeff()) &&
                Objects.equals(getAvgeff(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getAvgeff()) &&
                Objects.equals(getMinoperactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMinoperactmins()) &&
                Objects.equals(getMaxoperactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getMaxoperactmins()) &&
                Objects.equals(getAvgoperactmins(), procMk1100pk0qryMk721prodminsResponsePoutProdmins.getAvgoperactmins());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getClicod(),
                getGmtseq(),
                getGmtdes(),
                getMaklcn(),
                getSublcncod(),
                getProddate(),
                getMkline(),
                getNumoper(),
                getStarttime(),
                getEndtime(),
                getEffwrkmin(),
                getPrepmin(),
                getTarsewmin(),
                getPddminPrep(),
                getStdmin(),
                getPddmin(),
                getTargetqty(),
                getProdqty(),
                getEffpercent(),
                getRemarks(),
                getClinam(),
                getWstyle(),
                getWtotmins(),
                getWactmins(),
                getWhdactmins(),
                getWtotactmins(),
                getWtotgmtmin(),
                getSumminutes(),
                getSumpcs(),
                getSumtargetpcs(),
                getMineff(),
                getMaxeff(),
                getAvgeff(),
                getMinoperactmins(),
                getMaxoperactmins(),
                getAvgoperactmins());
    }
}