/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk400jobLoadperszeResponse implements Serializable {


    @ColumnAlias("poutJobSzeLoadQty")
    private List<ProcMk1100pk0Mk400jobLoadperszeResponsePoutJobSzeLoadQty> poutJobSzeLoadQty;

    public List<ProcMk1100pk0Mk400jobLoadperszeResponsePoutJobSzeLoadQty> getPoutJobSzeLoadQty() {
        return this.poutJobSzeLoadQty;
    }

    public void setPoutJobSzeLoadQty(List<ProcMk1100pk0Mk400jobLoadperszeResponsePoutJobSzeLoadQty> poutJobSzeLoadQty) {
        this.poutJobSzeLoadQty = poutJobSzeLoadQty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk400jobLoadperszeResponse)) return false;
        final ProcMk1100pk0Mk400jobLoadperszeResponse procMk1100pk0mk400jobLoadperszeResponse = (ProcMk1100pk0Mk400jobLoadperszeResponse) o;
        return Objects.equals(getPoutJobSzeLoadQty(), procMk1100pk0mk400jobLoadperszeResponse.getPoutJobSzeLoadQty());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutJobSzeLoadQty());
    }
}