/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0QryMk721prodminsResponse implements Serializable {


    @ColumnAlias("poutProdmins")
    private List<ProcMk1100pk0QryMk721prodminsResponsePoutProdmins> poutProdmins;

    public List<ProcMk1100pk0QryMk721prodminsResponsePoutProdmins> getPoutProdmins() {
        return this.poutProdmins;
    }

    public void setPoutProdmins(List<ProcMk1100pk0QryMk721prodminsResponsePoutProdmins> poutProdmins) {
        this.poutProdmins = poutProdmins;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0QryMk721prodminsResponse)) return false;
        final ProcMk1100pk0QryMk721prodminsResponse procMk1100pk0qryMk721prodminsResponse = (ProcMk1100pk0QryMk721prodminsResponse) o;
        return Objects.equals(getPoutProdmins(), procMk1100pk0qryMk721prodminsResponse.getPoutProdmins());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutProdmins());
    }
}