/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects implements Serializable {


    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("SZEDES")
    private String szedes;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("QTYCUT")
    private BigDecimal qtycut;

    @ColumnAlias("W_EMBQTY")
    private BigDecimal wembqty;

    @ColumnAlias("RBP")
    private BigDecimal rbp;

    @ColumnAlias("W_LOAD")
    private BigDecimal wload;

    @ColumnAlias("W_UNLOAD")
    private BigDecimal wunload;

    @ColumnAlias("RAP")
    private BigDecimal rap;

    @ColumnAlias("EXPCRT")
    private BigDecimal expcrt;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("TOTREQ")
    private BigInteger totreq;

    @ColumnAlias("TOTCUT")
    private BigInteger totcut;

    @ColumnAlias("W_TOTEMB")
    private BigInteger wtotemb;

    @ColumnAlias("TOTRBP")
    private BigInteger totrbp;

    @ColumnAlias("TOTLOAD")
    private BigInteger totload;

    @ColumnAlias("TOTUNLOAD")
    private BigInteger totunload;

    @ColumnAlias("TOTRAP")
    private BigInteger totrap;

    @ColumnAlias("TOTEXP")
    private BigInteger totexp;

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public String getSzedes() {
        return this.szedes;
    }

    public void setSzedes(String szedes) {
        this.szedes = szedes;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public BigDecimal getQtycut() {
        return this.qtycut;
    }

    public void setQtycut(BigDecimal qtycut) {
        this.qtycut = qtycut;
    }

    public BigDecimal getWembqty() {
        return this.wembqty;
    }

    public void setWembqty(BigDecimal wembqty) {
        this.wembqty = wembqty;
    }

    public BigDecimal getRbp() {
        return this.rbp;
    }

    public void setRbp(BigDecimal rbp) {
        this.rbp = rbp;
    }

    public BigDecimal getWload() {
        return this.wload;
    }

    public void setWload(BigDecimal wload) {
        this.wload = wload;
    }

    public BigDecimal getWunload() {
        return this.wunload;
    }

    public void setWunload(BigDecimal wunload) {
        this.wunload = wunload;
    }

    public BigDecimal getRap() {
        return this.rap;
    }

    public void setRap(BigDecimal rap) {
        this.rap = rap;
    }

    public BigDecimal getExpcrt() {
        return this.expcrt;
    }

    public void setExpcrt(BigDecimal expcrt) {
        this.expcrt = expcrt;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public BigInteger getTotreq() {
        return this.totreq;
    }

    public void setTotreq(BigInteger totreq) {
        this.totreq = totreq;
    }

    public BigInteger getTotcut() {
        return this.totcut;
    }

    public void setTotcut(BigInteger totcut) {
        this.totcut = totcut;
    }

    public BigInteger getWtotemb() {
        return this.wtotemb;
    }

    public void setWtotemb(BigInteger wtotemb) {
        this.wtotemb = wtotemb;
    }

    public BigInteger getTotrbp() {
        return this.totrbp;
    }

    public void setTotrbp(BigInteger totrbp) {
        this.totrbp = totrbp;
    }

    public BigInteger getTotload() {
        return this.totload;
    }

    public void setTotload(BigInteger totload) {
        this.totload = totload;
    }

    public BigInteger getTotunload() {
        return this.totunload;
    }

    public void setTotunload(BigInteger totunload) {
        this.totunload = totunload;
    }

    public BigInteger getTotrap() {
        return this.totrap;
    }

    public void setTotrap(BigInteger totrap) {
        this.totrap = totrap;
    }

    public BigInteger getTotexp() {
        return this.totexp;
    }

    public void setTotexp(BigInteger totexp) {
        this.totexp = totexp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects)) return false;
        final ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects = (ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects) o;
        return Objects.equals(getSzeseq(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getSzeseq()) &&
                Objects.equals(getSzedes(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getSzedes()) &&
                Objects.equals(getQtyord(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getQtyord()) &&
                Objects.equals(getQtycut(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getQtycut()) &&
                Objects.equals(getWembqty(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getWembqty()) &&
                Objects.equals(getRbp(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getRbp()) &&
                Objects.equals(getWload(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getWload()) &&
                Objects.equals(getWunload(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getWunload()) &&
                Objects.equals(getRap(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getRap()) &&
                Objects.equals(getExpcrt(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getExpcrt()) &&
                Objects.equals(getOrdnum(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getOrdnum()) &&
                Objects.equals(getGmtseq(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getGmtseq()) &&
                Objects.equals(getClrseq(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getClrseq()) &&
                Objects.equals(getTotreq(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotreq()) &&
                Objects.equals(getTotcut(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotcut()) &&
                Objects.equals(getWtotemb(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getWtotemb()) &&
                Objects.equals(getTotrbp(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotrbp()) &&
                Objects.equals(getTotload(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotload()) &&
                Objects.equals(getTotunload(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotunload()) &&
                Objects.equals(getTotrap(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotrap()) &&
                Objects.equals(getTotexp(), procMk1100pk0mk560qryMkrejectsResponsePoutMkRejects.getTotexp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSzeseq(),
                getSzedes(),
                getQtyord(),
                getQtycut(),
                getWembqty(),
                getRbp(),
                getWload(),
                getWunload(),
                getRap(),
                getExpcrt(),
                getOrdnum(),
                getGmtseq(),
                getClrseq(),
                getTotreq(),
                getTotcut(),
                getWtotemb(),
                getTotrbp(),
                getTotload(),
                getTotunload(),
                getTotrap(),
                getTotexp());
    }
}