/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0GetOrt150sizeResponse implements Serializable {


    @ColumnAlias("poutSizes")
    private List<ProcMk1100pk0GetOrt150sizeResponsePoutSizes> poutSizes;

    public List<ProcMk1100pk0GetOrt150sizeResponsePoutSizes> getPoutSizes() {
        return this.poutSizes;
    }

    public void setPoutSizes(List<ProcMk1100pk0GetOrt150sizeResponsePoutSizes> poutSizes) {
        this.poutSizes = poutSizes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0GetOrt150sizeResponse)) return false;
        final ProcMk1100pk0GetOrt150sizeResponse procMk1100pk0getOrt150sizeResponse = (ProcMk1100pk0GetOrt150sizeResponse) o;
        return Objects.equals(getPoutSizes(), procMk1100pk0getOrt150sizeResponse.getPoutSizes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutSizes());
    }
}