/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("CLRSEQ")
    private Byte clrseq;

    @ColumnAlias("QTYORD")
    private BigInteger qtyord;

    @ColumnAlias("W_GMTDES")
    private String wgmtdes;

    @ColumnAlias("W_GMTCAT")
    private String wgmtcat;

    @ColumnAlias("W_GMTTYP")
    private String wgmttyp;

    @ColumnAlias("W_CLRABB")
    private String wclrabb;

    @ColumnAlias("W_CUT")
    private BigInteger wcut;

    @ColumnAlias("W_CUTBAL")
    private BigInteger wcutbal;

    @ColumnAlias("W_LOAD")
    private BigInteger wload;

    @ColumnAlias("W_LOADBAL")
    private BigInteger wloadbal;

    @ColumnAlias("W_UNLOAD")
    private BigInteger wunload;

    @ColumnAlias("W_UNLOADBAL")
    private BigInteger wunloadbal;

    @ColumnAlias("W_CARTON")
    private BigInteger wcarton;

    @ColumnAlias("W_CARTONBAL")
    private BigInteger wcartonbal;

    @ColumnAlias("W_EXPORT")
    private BigInteger wexport;

    @ColumnAlias("W_EXPORTBAL")
    private BigInteger wexportbal;

    @ColumnAlias("W_EMB")
    private BigInteger wemb;

    @ColumnAlias("W_EMBBAL")
    private BigInteger wembbal;

    @ColumnAlias("W_PRINT")
    private BigInteger wprint;

    @ColumnAlias("W_PRINTBAL")
    private BigInteger wprintbal;

    @ColumnAlias("W_HEATPRESS")
    private BigInteger wheatpress;

    @ColumnAlias("W_HEATPRESSBAL")
    private BigInteger wheatpressbal;

    @ColumnAlias("M_HALTIND_CUT")
    private String mhaltindCut;

    @ColumnAlias("M_HALTIND_EMB")
    private String mhaltindEmb;

    @ColumnAlias("M_HALTIND_MAK")
    private String mhaltindMak;

    @ColumnAlias("M_HALTIND_PRT")
    private String mhaltindPrt;

    @ColumnAlias("M_HALTIND_CRT")
    private String mhaltindCrt;

    @ColumnAlias("M_HALTIND_EXP")
    private String mhaltindExp;

    @ColumnAlias("W_TOTORD")
    private BigInteger wtotord;

    @ColumnAlias("W_TOTCUT")
    private BigInteger wtotcut;

    @ColumnAlias("W_TOTCUTBAL")
    private BigInteger wtotcutbal;

    @ColumnAlias("W_TOTLOAD")
    private BigInteger wtotload;

    @ColumnAlias("W_TOTLOADBAL")
    private BigInteger wtotloadbal;

    @ColumnAlias("W_TOTULD")
    private BigInteger wtotuld;

    @ColumnAlias("W_TOTUNLOADBAL")
    private BigInteger wtotunloadbal;

    @ColumnAlias("W_TOTCARTON")
    private BigInteger wtotcarton;

    @ColumnAlias("W_TOTCARTONBAL")
    private BigInteger wtotcartonbal;

    @ColumnAlias("W_TOTEXP")
    private BigInteger wtotexp;

    @ColumnAlias("W_TOTEXPBAL")
    private BigInteger wtotexpbal;

    @ColumnAlias("W_TOTEMB")
    private BigInteger wtotemb;

    @ColumnAlias("W_TOTEMBBAL")
    private BigInteger wtotembbal;

    @ColumnAlias("W_TOTPRINT")
    private BigInteger wtotprint;

    @ColumnAlias("W_TOTPRINTBAL")
    private BigInteger wtotprintbal;

    @ColumnAlias("W_TOTHEATPRESS")
    private BigInteger wtotheatpress;

    @ColumnAlias("W_TOTHEATPRESSBAL")
    private BigInteger wtotheatpressbal;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public Byte getClrseq() {
        return this.clrseq;
    }

    public void setClrseq(Byte clrseq) {
        this.clrseq = clrseq;
    }

    public BigInteger getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(BigInteger qtyord) {
        this.qtyord = qtyord;
    }

    public String getWgmtdes() {
        return this.wgmtdes;
    }

    public void setWgmtdes(String wgmtdes) {
        this.wgmtdes = wgmtdes;
    }

    public String getWgmtcat() {
        return this.wgmtcat;
    }

    public void setWgmtcat(String wgmtcat) {
        this.wgmtcat = wgmtcat;
    }

    public String getWgmttyp() {
        return this.wgmttyp;
    }

    public void setWgmttyp(String wgmttyp) {
        this.wgmttyp = wgmttyp;
    }

    public String getWclrabb() {
        return this.wclrabb;
    }

    public void setWclrabb(String wclrabb) {
        this.wclrabb = wclrabb;
    }

    public BigInteger getWcut() {
        return this.wcut;
    }

    public void setWcut(BigInteger wcut) {
        this.wcut = wcut;
    }

    public BigInteger getWcutbal() {
        return this.wcutbal;
    }

    public void setWcutbal(BigInteger wcutbal) {
        this.wcutbal = wcutbal;
    }

    public BigInteger getWload() {
        return this.wload;
    }

    public void setWload(BigInteger wload) {
        this.wload = wload;
    }

    public BigInteger getWloadbal() {
        return this.wloadbal;
    }

    public void setWloadbal(BigInteger wloadbal) {
        this.wloadbal = wloadbal;
    }

    public BigInteger getWunload() {
        return this.wunload;
    }

    public void setWunload(BigInteger wunload) {
        this.wunload = wunload;
    }

    public BigInteger getWunloadbal() {
        return this.wunloadbal;
    }

    public void setWunloadbal(BigInteger wunloadbal) {
        this.wunloadbal = wunloadbal;
    }

    public BigInteger getWcarton() {
        return this.wcarton;
    }

    public void setWcarton(BigInteger wcarton) {
        this.wcarton = wcarton;
    }

    public BigInteger getWcartonbal() {
        return this.wcartonbal;
    }

    public void setWcartonbal(BigInteger wcartonbal) {
        this.wcartonbal = wcartonbal;
    }

    public BigInteger getWexport() {
        return this.wexport;
    }

    public void setWexport(BigInteger wexport) {
        this.wexport = wexport;
    }

    public BigInteger getWexportbal() {
        return this.wexportbal;
    }

    public void setWexportbal(BigInteger wexportbal) {
        this.wexportbal = wexportbal;
    }

    public BigInteger getWemb() {
        return this.wemb;
    }

    public void setWemb(BigInteger wemb) {
        this.wemb = wemb;
    }

    public BigInteger getWembbal() {
        return this.wembbal;
    }

    public void setWembbal(BigInteger wembbal) {
        this.wembbal = wembbal;
    }

    public BigInteger getWprint() {
        return this.wprint;
    }

    public void setWprint(BigInteger wprint) {
        this.wprint = wprint;
    }

    public BigInteger getWprintbal() {
        return this.wprintbal;
    }

    public void setWprintbal(BigInteger wprintbal) {
        this.wprintbal = wprintbal;
    }

    public BigInteger getWheatpress() {
        return this.wheatpress;
    }

    public void setWheatpress(BigInteger wheatpress) {
        this.wheatpress = wheatpress;
    }

    public BigInteger getWheatpressbal() {
        return this.wheatpressbal;
    }

    public void setWheatpressbal(BigInteger wheatpressbal) {
        this.wheatpressbal = wheatpressbal;
    }

    public String getMhaltindCut() {
        return this.mhaltindCut;
    }

    public void setMhaltindCut(String mhaltindCut) {
        this.mhaltindCut = mhaltindCut;
    }

    public String getMhaltindEmb() {
        return this.mhaltindEmb;
    }

    public void setMhaltindEmb(String mhaltindEmb) {
        this.mhaltindEmb = mhaltindEmb;
    }

    public String getMhaltindMak() {
        return this.mhaltindMak;
    }

    public void setMhaltindMak(String mhaltindMak) {
        this.mhaltindMak = mhaltindMak;
    }

    public String getMhaltindPrt() {
        return this.mhaltindPrt;
    }

    public void setMhaltindPrt(String mhaltindPrt) {
        this.mhaltindPrt = mhaltindPrt;
    }

    public String getMhaltindCrt() {
        return this.mhaltindCrt;
    }

    public void setMhaltindCrt(String mhaltindCrt) {
        this.mhaltindCrt = mhaltindCrt;
    }

    public String getMhaltindExp() {
        return this.mhaltindExp;
    }

    public void setMhaltindExp(String mhaltindExp) {
        this.mhaltindExp = mhaltindExp;
    }

    public BigInteger getWtotord() {
        return this.wtotord;
    }

    public void setWtotord(BigInteger wtotord) {
        this.wtotord = wtotord;
    }

    public BigInteger getWtotcut() {
        return this.wtotcut;
    }

    public void setWtotcut(BigInteger wtotcut) {
        this.wtotcut = wtotcut;
    }

    public BigInteger getWtotcutbal() {
        return this.wtotcutbal;
    }

    public void setWtotcutbal(BigInteger wtotcutbal) {
        this.wtotcutbal = wtotcutbal;
    }

    public BigInteger getWtotload() {
        return this.wtotload;
    }

    public void setWtotload(BigInteger wtotload) {
        this.wtotload = wtotload;
    }

    public BigInteger getWtotloadbal() {
        return this.wtotloadbal;
    }

    public void setWtotloadbal(BigInteger wtotloadbal) {
        this.wtotloadbal = wtotloadbal;
    }

    public BigInteger getWtotuld() {
        return this.wtotuld;
    }

    public void setWtotuld(BigInteger wtotuld) {
        this.wtotuld = wtotuld;
    }

    public BigInteger getWtotunloadbal() {
        return this.wtotunloadbal;
    }

    public void setWtotunloadbal(BigInteger wtotunloadbal) {
        this.wtotunloadbal = wtotunloadbal;
    }

    public BigInteger getWtotcarton() {
        return this.wtotcarton;
    }

    public void setWtotcarton(BigInteger wtotcarton) {
        this.wtotcarton = wtotcarton;
    }

    public BigInteger getWtotcartonbal() {
        return this.wtotcartonbal;
    }

    public void setWtotcartonbal(BigInteger wtotcartonbal) {
        this.wtotcartonbal = wtotcartonbal;
    }

    public BigInteger getWtotexp() {
        return this.wtotexp;
    }

    public void setWtotexp(BigInteger wtotexp) {
        this.wtotexp = wtotexp;
    }

    public BigInteger getWtotexpbal() {
        return this.wtotexpbal;
    }

    public void setWtotexpbal(BigInteger wtotexpbal) {
        this.wtotexpbal = wtotexpbal;
    }

    public BigInteger getWtotemb() {
        return this.wtotemb;
    }

    public void setWtotemb(BigInteger wtotemb) {
        this.wtotemb = wtotemb;
    }

    public BigInteger getWtotembbal() {
        return this.wtotembbal;
    }

    public void setWtotembbal(BigInteger wtotembbal) {
        this.wtotembbal = wtotembbal;
    }

    public BigInteger getWtotprint() {
        return this.wtotprint;
    }

    public void setWtotprint(BigInteger wtotprint) {
        this.wtotprint = wtotprint;
    }

    public BigInteger getWtotprintbal() {
        return this.wtotprintbal;
    }

    public void setWtotprintbal(BigInteger wtotprintbal) {
        this.wtotprintbal = wtotprintbal;
    }

    public BigInteger getWtotheatpress() {
        return this.wtotheatpress;
    }

    public void setWtotheatpress(BigInteger wtotheatpress) {
        this.wtotheatpress = wtotheatpress;
    }

    public BigInteger getWtotheatpressbal() {
        return this.wtotheatpressbal;
    }

    public void setWtotheatpressbal(BigInteger wtotheatpressbal) {
        this.wtotheatpressbal = wtotheatpressbal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet)) return false;
        final ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet procMk1100pk0mk570getProdDetailsResponsePoutProdDet = (ProcMk1100pk0Mk570getProdDetailsResponsePoutProdDet) o;
        return Objects.equals(getOrdnum(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getOrdnum()) &&
                Objects.equals(getGmtseq(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getGmtseq()) &&
                Objects.equals(getClrseq(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getClrseq()) &&
                Objects.equals(getQtyord(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getQtyord()) &&
                Objects.equals(getWgmtdes(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWgmtdes()) &&
                Objects.equals(getWgmtcat(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWgmtcat()) &&
                Objects.equals(getWgmttyp(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWgmttyp()) &&
                Objects.equals(getWclrabb(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWclrabb()) &&
                Objects.equals(getWcut(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWcut()) &&
                Objects.equals(getWcutbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWcutbal()) &&
                Objects.equals(getWload(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWload()) &&
                Objects.equals(getWloadbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWloadbal()) &&
                Objects.equals(getWunload(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWunload()) &&
                Objects.equals(getWunloadbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWunloadbal()) &&
                Objects.equals(getWcarton(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWcarton()) &&
                Objects.equals(getWcartonbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWcartonbal()) &&
                Objects.equals(getWexport(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWexport()) &&
                Objects.equals(getWexportbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWexportbal()) &&
                Objects.equals(getWemb(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWemb()) &&
                Objects.equals(getWembbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWembbal()) &&
                Objects.equals(getWprint(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWprint()) &&
                Objects.equals(getWprintbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWprintbal()) &&
                Objects.equals(getWheatpress(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWheatpress()) &&
                Objects.equals(getWheatpressbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWheatpressbal()) &&
                Objects.equals(getMhaltindCut(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindCut()) &&
                Objects.equals(getMhaltindEmb(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindEmb()) &&
                Objects.equals(getMhaltindMak(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindMak()) &&
                Objects.equals(getMhaltindPrt(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindPrt()) &&
                Objects.equals(getMhaltindCrt(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindCrt()) &&
                Objects.equals(getMhaltindExp(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getMhaltindExp()) &&
                Objects.equals(getWtotord(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotord()) &&
                Objects.equals(getWtotcut(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotcut()) &&
                Objects.equals(getWtotcutbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotcutbal()) &&
                Objects.equals(getWtotload(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotload()) &&
                Objects.equals(getWtotloadbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotloadbal()) &&
                Objects.equals(getWtotuld(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotuld()) &&
                Objects.equals(getWtotunloadbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotunloadbal()) &&
                Objects.equals(getWtotcarton(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotcarton()) &&
                Objects.equals(getWtotcartonbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotcartonbal()) &&
                Objects.equals(getWtotexp(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotexp()) &&
                Objects.equals(getWtotexpbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotexpbal()) &&
                Objects.equals(getWtotemb(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotemb()) &&
                Objects.equals(getWtotembbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotembbal()) &&
                Objects.equals(getWtotprint(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotprint()) &&
                Objects.equals(getWtotprintbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotprintbal()) &&
                Objects.equals(getWtotheatpress(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotheatpress()) &&
                Objects.equals(getWtotheatpressbal(), procMk1100pk0mk570getProdDetailsResponsePoutProdDet.getWtotheatpressbal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getGmtseq(),
                getClrseq(),
                getQtyord(),
                getWgmtdes(),
                getWgmtcat(),
                getWgmttyp(),
                getWclrabb(),
                getWcut(),
                getWcutbal(),
                getWload(),
                getWloadbal(),
                getWunload(),
                getWunloadbal(),
                getWcarton(),
                getWcartonbal(),
                getWexport(),
                getWexportbal(),
                getWemb(),
                getWembbal(),
                getWprint(),
                getWprintbal(),
                getWheatpress(),
                getWheatpressbal(),
                getMhaltindCut(),
                getMhaltindEmb(),
                getMhaltindMak(),
                getMhaltindPrt(),
                getMhaltindCrt(),
                getMhaltindExp(),
                getWtotord(),
                getWtotcut(),
                getWtotcutbal(),
                getWtotload(),
                getWtotloadbal(),
                getWtotuld(),
                getWtotunloadbal(),
                getWtotcarton(),
                getWtotcartonbal(),
                getWtotexp(),
                getWtotexpbal(),
                getWtotemb(),
                getWtotembbal(),
                getWtotprint(),
                getWtotprintbal(),
                getWtotheatpress(),
                getWtotheatpressbal());
    }
}