/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0Mk560qryMkrejectsResponse implements Serializable {


    @ColumnAlias("poutMkRejects")
    private List<ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects> poutMkRejects;

    public List<ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects> getPoutMkRejects() {
        return this.poutMkRejects;
    }

    public void setPoutMkRejects(List<ProcMk1100pk0Mk560qryMkrejectsResponsePoutMkRejects> poutMkRejects) {
        this.poutMkRejects = poutMkRejects;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0Mk560qryMkrejectsResponse)) return false;
        final ProcMk1100pk0Mk560qryMkrejectsResponse procMk1100pk0mk560qryMkrejectsResponse = (ProcMk1100pk0Mk560qryMkrejectsResponse) o;
        return Objects.equals(getPoutMkRejects(), procMk1100pk0mk560qryMkrejectsResponse.getPoutMkRejects());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMkRejects());
    }
}