/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcMk1100pk0GetGmtColourDetailsResponse implements Serializable {


    @ColumnAlias("poutGmtclrList")
    private List<ProcMk1100pk0GetGmtColourDetailsResponsePoutGmtclrList> poutGmtclrList;

    public List<ProcMk1100pk0GetGmtColourDetailsResponsePoutGmtclrList> getPoutGmtclrList() {
        return this.poutGmtclrList;
    }

    public void setPoutGmtclrList(List<ProcMk1100pk0GetGmtColourDetailsResponsePoutGmtclrList> poutGmtclrList) {
        this.poutGmtclrList = poutGmtclrList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcMk1100pk0GetGmtColourDetailsResponse)) return false;
        final ProcMk1100pk0GetGmtColourDetailsResponse procMk1100pk0getGmtColourDetailsResponse = (ProcMk1100pk0GetGmtColourDetailsResponse) o;
        return Objects.equals(getPoutGmtclrList(), procMk1100pk0getGmtColourDetailsResponse.getPoutGmtclrList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutGmtclrList());
    }
}