/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Sr2680pk0checkBeforeDwnldPatternResponse implements Serializable {


    @ColumnAlias("poutLectracode")
    private String poutLectracode;

    @ColumnAlias("poutVersionno")
    private Integer poutVersionno;

    @ColumnAlias("poutGmtseq")
    private String poutGmtseq;

    @ColumnAlias("poutPattypecode")
    private String poutPattypecode;

    @ColumnAlias("poutFilename")
    private String poutFilename;

    public String getPoutLectracode() {
        return this.poutLectracode;
    }

    public void setPoutLectracode(String poutLectracode) {
        this.poutLectracode = poutLectracode;
    }

    public Integer getPoutVersionno() {
        return this.poutVersionno;
    }

    public void setPoutVersionno(Integer poutVersionno) {
        this.poutVersionno = poutVersionno;
    }

    public String getPoutGmtseq() {
        return this.poutGmtseq;
    }

    public void setPoutGmtseq(String poutGmtseq) {
        this.poutGmtseq = poutGmtseq;
    }

    public String getPoutPattypecode() {
        return this.poutPattypecode;
    }

    public void setPoutPattypecode(String poutPattypecode) {
        this.poutPattypecode = poutPattypecode;
    }

    public String getPoutFilename() {
        return this.poutFilename;
    }

    public void setPoutFilename(String poutFilename) {
        this.poutFilename = poutFilename;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Sr2680pk0checkBeforeDwnldPatternResponse)) return false;
        final Sr2680pk0checkBeforeDwnldPatternResponse sr2680pk0checkBeforeDwnldPatternResponse = (Sr2680pk0checkBeforeDwnldPatternResponse) o;
        return Objects.equals(getPoutLectracode(), sr2680pk0checkBeforeDwnldPatternResponse.getPoutLectracode()) &&
                Objects.equals(getPoutVersionno(), sr2680pk0checkBeforeDwnldPatternResponse.getPoutVersionno()) &&
                Objects.equals(getPoutGmtseq(), sr2680pk0checkBeforeDwnldPatternResponse.getPoutGmtseq()) &&
                Objects.equals(getPoutPattypecode(), sr2680pk0checkBeforeDwnldPatternResponse.getPoutPattypecode()) &&
                Objects.equals(getPoutFilename(), sr2680pk0checkBeforeDwnldPatternResponse.getPoutFilename());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLectracode(),
                getPoutVersionno(),
                getPoutGmtseq(),
                getPoutPattypecode(),
                getPoutFilename());
    }
}