/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Sy2110pk0getCroquisPathResponse implements Serializable {


    @ColumnAlias("poutCroqpath")
    private String poutCroqpath;

    @ColumnAlias("poutWarningmsg")
    private String poutWarningmsg;

    public String getPoutCroqpath() {
        return this.poutCroqpath;
    }

    public void setPoutCroqpath(String poutCroqpath) {
        this.poutCroqpath = poutCroqpath;
    }

    public String getPoutWarningmsg() {
        return this.poutWarningmsg;
    }

    public void setPoutWarningmsg(String poutWarningmsg) {
        this.poutWarningmsg = poutWarningmsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Sy2110pk0getCroquisPathResponse)) return false;
        final Sy2110pk0getCroquisPathResponse sy2110pk0getCroquisPathResponse = (Sy2110pk0getCroquisPathResponse) o;
        return Objects.equals(getPoutCroqpath(), sy2110pk0getCroquisPathResponse.getPoutCroqpath()) &&
                Objects.equals(getPoutWarningmsg(), sy2110pk0getCroquisPathResponse.getPoutWarningmsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCroqpath(),
                getPoutWarningmsg());
    }
}