/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Srt2671 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SRT2671`")
@IdClass(Srt2671Id.class)
public class Srt2671 implements Serializable {

    private Byte versionno;
    private String pattypecode;
    private String lectracode;
    private String gmtseq;
    private String filename;
    private String sts;
    private String uploadedby;
    private LocalDateTime uploadeddate;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] patternfile;
    private String remarks;
    private String checkoutby;
    private LocalDateTime checkoutdate;
    private String checkouthost;
    private String checkoutremarks;
    private String pattfeat;
    private String stylecodes;
    private String requestnos;
    private String patternblock;
    private String blockdefn;
    private String blockselectby;
    private String blockunselectby;
    private LocalDateTime blockdate;
    private LocalDateTime blockunselectdate;

    @Id
    @Column(name = "`VERSIONNO`", nullable = false, scale = 0, precision = 2)
    public Byte getVersionno() {
        return this.versionno;
    }

    public void setVersionno(Byte versionno) {
        this.versionno = versionno;
    }

    @Id
    @Column(name = "`PATTYPECODE`", nullable = false, length = 3)
    public String getPattypecode() {
        return this.pattypecode;
    }

    public void setPattypecode(String pattypecode) {
        this.pattypecode = pattypecode;
    }

    @Id
    @Column(name = "`LECTRACODE`", nullable = false, length = 12)
    public String getLectracode() {
        return this.lectracode;
    }

    public void setLectracode(String lectracode) {
        this.lectracode = lectracode;
    }

    @Id
    @Column(name = "`GMTSEQ`", nullable = false, length = 2)
    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    @Column(name = "`FILENAME`", nullable = false, length = 15)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name = "`STS`", nullable = false, length = 3)
    public String getSts() {
        return this.sts;
    }

    public void setSts(String sts) {
        this.sts = sts;
    }

    @Column(name = "`UPLOADEDBY`", nullable = true, length = 6)
    public String getUploadedby() {
        return this.uploadedby;
    }

    public void setUploadedby(String uploadedby) {
        this.uploadedby = uploadedby;
    }

    @Column(name = "`UPLOADEDDATE`", nullable = true)
    public LocalDateTime getUploadeddate() {
        return this.uploadeddate;
    }

    public void setUploadeddate(LocalDateTime uploadeddate) {
        this.uploadeddate = uploadeddate;
    }

    @Column(name = "`PATTERNFILE`", nullable = true)
    public byte[] getPatternfile() {
        return this.patternfile;
    }

    public void setPatternfile(byte[] patternfile) {
        this.patternfile = patternfile;
    }

    @Column(name = "`REMARKS`", nullable = true, length = 256)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "`CHECKOUTBY`", nullable = true, length = 6)
    public String getCheckoutby() {
        return this.checkoutby;
    }

    public void setCheckoutby(String checkoutby) {
        this.checkoutby = checkoutby;
    }

    @Column(name = "`CHECKOUTDATE`", nullable = true)
    public LocalDateTime getCheckoutdate() {
        return this.checkoutdate;
    }

    public void setCheckoutdate(LocalDateTime checkoutdate) {
        this.checkoutdate = checkoutdate;
    }

    @Column(name = "`CHECKOUTHOST`", nullable = true, length = 30)
    public String getCheckouthost() {
        return this.checkouthost;
    }

    public void setCheckouthost(String checkouthost) {
        this.checkouthost = checkouthost;
    }

    @Column(name = "`CHECKOUTREMARKS`", nullable = true, length = 256)
    public String getCheckoutremarks() {
        return this.checkoutremarks;
    }

    public void setCheckoutremarks(String checkoutremarks) {
        this.checkoutremarks = checkoutremarks;
    }

    @Column(name = "`PATTFEAT`", nullable = true, length = 256)
    public String getPattfeat() {
        return this.pattfeat;
    }

    public void setPattfeat(String pattfeat) {
        this.pattfeat = pattfeat;
    }

    @Column(name = "`STYLECODES`", nullable = true, length = 30)
    public String getStylecodes() {
        return this.stylecodes;
    }

    public void setStylecodes(String stylecodes) {
        this.stylecodes = stylecodes;
    }

    @Column(name = "`REQUESTNOS`", nullable = true, length = 128)
    public String getRequestnos() {
        return this.requestnos;
    }

    public void setRequestnos(String requestnos) {
        this.requestnos = requestnos;
    }

    @Column(name = "`PATTERNBLOCK`", nullable = true, length = 1)
    public String getPatternblock() {
        return this.patternblock;
    }

    public void setPatternblock(String patternblock) {
        this.patternblock = patternblock;
    }

    @Column(name = "`BLOCKDEFN`", nullable = true, length = 30)
    public String getBlockdefn() {
        return this.blockdefn;
    }

    public void setBlockdefn(String blockdefn) {
        this.blockdefn = blockdefn;
    }

    @Column(name = "`BLOCKSELECTBY`", nullable = true, length = 6)
    public String getBlockselectby() {
        return this.blockselectby;
    }

    public void setBlockselectby(String blockselectby) {
        this.blockselectby = blockselectby;
    }

    @Column(name = "`BLOCKUNSELECTBY`", nullable = true, length = 6)
    public String getBlockunselectby() {
        return this.blockunselectby;
    }

    public void setBlockunselectby(String blockunselectby) {
        this.blockunselectby = blockunselectby;
    }

    @Column(name = "`BLOCKDATE`", nullable = true)
    public LocalDateTime getBlockdate() {
        return this.blockdate;
    }

    public void setBlockdate(LocalDateTime blockdate) {
        this.blockdate = blockdate;
    }

    @Column(name = "`BLOCKUNSELECTDATE`", nullable = true)
    public LocalDateTime getBlockunselectdate() {
        return this.blockunselectdate;
    }

    public void setBlockunselectdate(LocalDateTime blockunselectdate) {
        this.blockunselectdate = blockunselectdate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Srt2671)) return false;
        final Srt2671 srt2671 = (Srt2671) o;
        return Objects.equals(getVersionno(), srt2671.getVersionno()) &&
                Objects.equals(getPattypecode(), srt2671.getPattypecode()) &&
                Objects.equals(getLectracode(), srt2671.getLectracode()) &&
                Objects.equals(getGmtseq(), srt2671.getGmtseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVersionno(),
                getPattypecode(),
                getLectracode(),
                getGmtseq());
    }
}