/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Srt2671Id implements Serializable {

    private Byte versionno;
    private String pattypecode;
    private String lectracode;
    private String gmtseq;

    public Byte getVersionno() {
        return this.versionno;
    }

    public void setVersionno(Byte versionno) {
        this.versionno = versionno;
    }

    public String getPattypecode() {
        return this.pattypecode;
    }

    public void setPattypecode(String pattypecode) {
        this.pattypecode = pattypecode;
    }

    public String getLectracode() {
        return this.lectracode;
    }

    public void setLectracode(String lectracode) {
        this.lectracode = lectracode;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Srt2671)) return false;
        final Srt2671 srt2671 = (Srt2671) o;
        return Objects.equals(getVersionno(), srt2671.getVersionno()) &&
                Objects.equals(getPattypecode(), srt2671.getPattypecode()) &&
                Objects.equals(getLectracode(), srt2671.getLectracode()) &&
                Objects.equals(getGmtseq(), srt2671.getGmtseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVersionno(),
                getPattypecode(),
                getLectracode(),
                getGmtseq());
    }
}