/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.mu.cmt.pfs.pfsdb.models.query.*;

public interface PfsdbQueryExecutorService {

    QryCanViewOrdStakeResponse executeQryCanViewOrdStake();

    QrySy9200pk0callOr210Response executeQrySy9200pk0CallOR210(String potherParams);

    QrySy9200pk0getOrdRoutingUrlResponse executeQrySy9200pk0GetOrdRoutingUrl(String potherParams);

}