/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

import com.mu.cmt.pfs.pfsdb.models.query.*;

@Service
public class PfsdbQueryExecutorServiceImpl implements PfsdbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PfsdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("pfsdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QryCanViewOrdStakeResponse executeQryCanViewOrdStake() {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("qryCanViewOrdStake", params, QryCanViewOrdStakeResponse.class);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QrySy9200pk0callOr210Response executeQrySy9200pk0CallOR210(String potherParams) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("pOtherParams", potherParams);

        return queryExecutor.executeNamedQuery("qrySy9200pk0CallOR210", params, QrySy9200pk0callOr210Response.class);
    }

    @Transactional(value = "pfsdbTransactionManager", readOnly = true)
    @Override
    public QrySy9200pk0getOrdRoutingUrlResponse executeQrySy9200pk0GetOrdRoutingUrl(String potherParams) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("pOtherParams", potherParams);

        return queryExecutor.executeNamedQuery("qrySy9200pk0GetOrdRoutingUrl", params, QrySy9200pk0getOrdRoutingUrlResponse.class);
    }

}